### ISSUE TITLE
issue with cucumber 0.4.0?

### ISSUE THREAD

**Issue by jonforums** [luislavena/win32console#1]
running a simple 'cucumber' gives the following on 1.9.1p243 (mingw32)

win32console-1.2.0-x86-mingw32/lib/Win32/Console/ANSI.rb:325:invalid multibyte char (US-ASCII) (SyntaxError)

full trace....

C:\Documents and Settings\Jon\My Documents>ruby --version
ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]

C:\Documents and Settings\Jon\My Documents>gem --version
1.3.5

<pre><code>
C:\Documents and Settings\Jon\My Documents>cucumber
D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `require': D:/ruby
19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/lib/Win32/Console/ANSI.rb:325:
invalid multibyte char (US-ASCII) (SyntaxError)
D:/ruby19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/lib/Win32/Console/ANSI.r
b:325: invalid multibyte char (US-ASCII)
D:/ruby19/lib/ruby/gems/1.9.1/gems/win32console-1.2.0-x86-mingw32/lib/Win32/Console/ANSI.r
b:325: syntax error, unexpected $end, expecting ')'
              s.tr!("ÇüéâäàåçêëèïìÄÅÉæÆôöòûùÿÖÜ¢¥₧ƒü...
                       ^
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/lib/cucumber/formatter/ansi
color.rb:7:in `<top (required)>'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/lib/cucumber/formatter/cons
ole.rb:1:in `<top (required)>'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/lib/cucumber/formatter/pret
ty.rb:1:in `<top (required)>'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/lib/cucumber/cli/language_h
elp_formatter.rb:1:in `<top (required)>'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/polyglot-0.2.9/lib/polyglot.rb:70:in `requ
ire'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/lib/cucumber/cli/main.rb:8:
in `<top (required)>'
        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/bin/cucumber:6:in `require'

        from D:/ruby19/lib/ruby/gems/1.9.1/gems/cucumber-0.4.0/bin/cucumber:6:in `<top (re
quired)>'
        from D:/ruby19/bin/cucumber:19:in `load'
        from D:/ruby19/bin/cucumber:19:in `<main>'
</code>
</pre>

**Comment by luislavena** [comment]
Yes, this has been reported and fixed in a fork, which will be integrated pretty soon.

**Comment by luislavena** [comment]
Closed by commit 90e428f47eee733023ecfae4f5850a026802182b
