### ISSUE TITLE
win32console breaks "puts" when used with open3

### ISSUE THREAD

**Issue by skrebbel** [luislavena/win32console#10]
Hi! 

When using with win32console and open3, i experienced some strange behaviour. Basically, `puts` stops outputting anything from the moment a process is run with open3 onwards. Not requiring win32console makes everything work as expected.

I've created an example on https://gist.github.com/894095

**Comment by luislavena** [comment]
Please stop using win32console since it has been deprecated in favor of ANSICON.

http://blog.mmediasys.com/2010/11/24/we-all-love-colors/

That will solve your issues.

**Comment by skrebbel** [comment]
Oh, nice; I'll check that out :-)

BTW, maybe a good idea to put this info in the readme? :-)
