### ISSUE TITLE
1.3.1 requires developer tools to be installed when 1.3.0 didn't

### ISSUE THREAD

**Issue by gshutler** [luislavena/win32console#13]
For a patch release that seems like a major change.

I don't know if it's too late to go back on the version number but it seems like it should be 1.4.0 if not 2.0.0? I fixed my immediate problem by strictly requiring 1.3.0.

I had a look and I can't see which commit may have introduced this so it could be an upstream thing. I'm happy to investigate if it isn't apparent how this came in to anyone.

**Comment by luislavena** [comment]
> For a patch release that seems like a major change.

No, is not, please see the list of changes here:

https://github.com/luislavena/win32console/blob/master/History.txt#L1-4

> I don't know if it's too late to go back on the version number but it seems like it should be 1.4.0 if not 2.0.0? I fixed my immediate problem by strictly requiring 1.3.0.

The issue has nothing to do with features but is the gem platform what matters.

1.3.0 was released on both `ruby` and pre-compiled versions, as listed here:

https://rubygems.org/gems/win32console

As I mentioned on pull #12 (the one that implemented the feature described in the History file), I didn't had the time to release a binary version over the past few days, considering I was also doing a release of RubyInstaller 1.9.3.

Will find the time to do release of the binaries if time allows, but you can revert to use 1.3.0 as none forces you to use the latest one.

**Comment by gshutler** [comment]
Ah, my apologies. I didn't realise the pre-compilation would be needed without any visible change in the code. I should have looked in the pull request too.

Thanks for your time.

**Comment by luislavena** [comment]
>  I didn't realise the pre-compilation would be needed without any visible change in the code.

Every new gem requires it's pre-compiled counterpart. pre-compiled binaries are not committed to the repository (and shouldn't) so compilation is required on every gem release.

**Comment by luislavena** [comment]
@gshutler just pushed the pre-compiled versions of this gem to rubygems:

https://rubygems.org/gems/win32console

**Comment by gshutler** [comment]
Awesome, thanks very much. I haven't worked on gems including a C component before so I wasn't aware of what was required to manage them. Sorry for flipping my shit through ignorance.
