### ISSUE TITLE
Invalid handle error

### ISSUE THREAD

**Issue by w14349** [luislavena/win32console#15]
If i use the previous version of the gem (1.3.0) I have no issues, but when using the latest version I get the following error:

c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console.rb:210:in `GetConsoleScreenBufferInfo': The handle is invalid.
 (RuntimeError)
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console.rb:210:in`Attr'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console.rb:35:in `initialize'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:88:in`new'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:88:in `initialize'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:348:in`new'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/Win32/Console/ANSI.rb:348:in `<top (required)>'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from c:/Ruby193/lib/ruby/gems/1.9.1/gems/win32console-1.3.1-x86-mingw32/lib/win32console.rb:1:in`<top (required)>'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `require'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in`rescue in require'
    from c:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'

**Comment by luislavena** [comment]
See #14

Patches are welcome.
