### ISSUE TITLE
win32console 1.3.2 loadError, due to missing 2.0/Console_ext

### ISSUE THREAD

**Issue by pmw57** [luislavena/win32console#17]
When running Ruby 2.0, win32console 1.3.2 attempts to require 2.0/Console_ext which doesn't exist.

Using the Ruby DevKit and using that to install win32console results in things successfully working.

**Comment by luislavena** [comment]
Usage of win32console against ruby 2.0 is not recommended. 

Ruby 2.0 already includes ANSI coloring builtin. 

This gem has been deprecated and no further updates will be made.
