### ISSUE TITLE
Autotest+RSpec2+Win32console = no color

### ISSUE THREAD

**Issue by arvicco** [luislavena/win32console#9]
I have the same problem with the combination above with Ruby 1.9.2 on Windows XP, as described here:
http://www.ruby-forum.com/topic/205569

Calling Rspec directly produces colored output, but autotest spits out ANSI sequences. The issue was supposed to be closed with win32console 1.3.0, but obviously it didn't for the above-mentioned combination.

---

Y:\Dev\apps\win\win_exp>ruby -v
ruby 1.9.2p0 (2010-08-18) [i386-mingw32]

Y:\Dev\apps\win\win_exp>gem list
**\* LOCAL GEMS ***
autotest (4.4.1)
autotest-growl (0.2.6)
builder (2.1.2)
bundler (1.0.2)
cucumber (0.9.2)
diff-lcs (1.1.2)
gherkin (2.2.9 x86-mingw32)
json (1.4.6 x86-mingw32)
minitest (1.6.0)
rake (0.8.7)
rspec (2.0.1, 1.3.1)
rspec-core (2.0.1)
rspec-expectations (2.0.1)
rspec-mocks (2.0.1)
term-ansicolor (1.0.5)
test-unit (2.1.1)
win32console (1.3.0 x86-mingw32)

**Comment by luislavena** [comment]
Indeed, this happens with autotest gem, but ZenTest gem (which provides autotest command) doesn't work either.

Will investigate.

**Comment by luislavena** [comment]
Hello,

Seems that autotest is reading a single character (`getc`) from the rspec output and then printing single bytes instead of respecting possible unicode or escape sequences:

http://github.com/grosser/autotest/blob/master/lib/autotest.rb#L315-316

Can you try changing `print` to `$stdout.write` and let me know.

print is not been controlled/managed by `Win32::Console::ANSI`

There are still some unicode and double byte issues, but let's see if this fix the current problem.

Modify the existing gem and let me know.

**Comment by luislavena** [comment]
Hello,

Wanted to let you know that I believe have discovered the root of the issue and is around the above indicated lines.

I also believe this way of getting and outputting the pipe output will affect accented characters for Unicode tests/specs.

Moving this higher in the priority to be worked out.

Apologizes for any inconvenience on this.

**Comment by arvicco** [comment]
Thanks, Luis!

I haven't got around to patching autotest proper, for now I'm just pushing autotest output on Windows through simple ANSI pipe. Works well enough for now, so not a big priority atm.

**Comment by voxik** [comment]
See https://github.com/grosser/autotest/issues#issue/5

**Comment by luislavena** [comment]
Please see the thread about deprecating win32console and replace by ANSICON:

http://groups.google.com/group/rubyinstaller/browse_thread/thread/2d2a62db7281509a/

That will fix these issues but still we are looking to resolve accented characters.

**Comment by arvicco** [comment]
Actually, I'm using non-Western codepages intensively, so ANSICON does not seem to work for me at all in conjunction with RSpec/Autotest...

**Comment by luislavena** [comment]
Well, no work has been done to fix this yet, please bear with us while we explore solutions.

**Comment by luislavena** [comment]
Hello, win32console has been deprecated in favor of ANSICON.

RSpec 2.2 and Cucumber already integrated the needed changes for this to work.

If you want to get familiarized with ANSICON, please read the following post in my blog:

http://blog.mmediasys.com/2010/11/24/we-all-love-colors/

ANSICON has now been fixed to resolve the accented character issue (which was Ruby) and newer versions of Ruby will handle that properly.

Closing this out. Thank you for your report.

**Comment by arvicco** [comment]
I understand your position, but ANSICON does not solve this issue, unfortunately.
In ansicon-enabled console, autotest still shows no color and reports:
   You must 'gem install win32console' to use colour on Windows

**Comment by luislavena** [comment]
Hello, you're using an old version of rspec2. rspec 2.2 includes ANSICON support.

Also, please upgrade to ZenTest 4.4.2, as it includes the corrections needed by rspec2 to work properly.

It does solve the issue, as I'm using it right now :-)

**Comment by arvicco** [comment]
Indeed, it does work now. Thanks a lot, Luis!
